# Generated by Django 2.0.3 on 2018-04-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.CharField(blank=True, help_text='description of the destination URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
