# Generated by Django 2.0.5 on 2018-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0003_auto_20180401_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={},
        ),
        migrations.AddField(
            model_name='redirect',
            name='burl',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='redirect',
            index=models.Index(fields=['burl', 'url'], name='redirects_r_burl_974555_idx'),
        ),
    ]
