# Generated by Django 2.0.5 on 2018-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0004_auto_20180521_0813'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='redirect',
            name='redirects_r_burl_974555_idx',
        ),
        migrations.AlterField(
            model_name='redirect',
            name='url',
            field=models.URLField(db_index=True, verbose_name='URL'),
        ),
    ]
