# Generated by Django 2.0.5 on 2018-05-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0005_auto_20180521_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='burl',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
