# Generated by Django 2.0.5 on 2019-01-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0007_auto_20190112_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='random',
            field=models.NullBooleanField(default=False),
        ),
    ]
