# Generated by Django 2.0.5 on 2019-01-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0008_auto_20190115_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='random',
            field=models.BooleanField(default=False),
        ),
    ]
